---
- name: create user for localhost
  hosts: localhost
  tasks:
    - name: create a user 
      user:
        name: siman
        group: root
        comment: testuser
        groups: wheel        #add the user in wheel group to make sudo user 
        append: true
        state: present
